create app Group and code model
makmoulsoufiane/Systeme-Management-Student-v2 pull request #10
Opened 2024-12-21 10:16 UTC by makmoulsoufiane

This pull request introduces a new **Group model**, which is based on our diagram representation. The model includes the following attributes:

**id_group:** An auto-incrementing primary key.
**year_of_creation**: An integer field representing the year the group was created.

2024-12-21 21:29 UTC, Boubaker17 approved these changes
Everything is good in Group app

2024-12-23 18:47 UTC, Boubaker17 approved these changes

2024-12-23 19:47 UTC, Boubaker17 approved these changes

2024-12-23 19:50 UTC, Boubaker17 requested changes
I change conflict things files in settings.py and pycache
try to make another pull request to merge it again

2024-12-23 19:59 UTC, makmoulsoufiane commented
If you solve the conflict you can mergit directly

2024-12-23 20:38 UTC, merged